#!/bin/sh
_out="${OUT:-jumpstart.sh}"
truncate --size 0 "$_out"
include() {
  if [ "$1" = "-n" ]; then
    np=1
    shift
  else
    unset np
  fi

  for ch in "include/"${1%.chunk.sh}; do
    if [ -z "$np" ]; then
      printf "#include ${ch%.chunk.sh}\n" >> "$_out"
    fi
    cat "${ch%.chunk.sh}.chunk.sh" >> "$_out"
    printf "\n\n" >> "$_out"
  done
}


include -n shebang
include -n autogenerated_warn

if [ -n "$SHELLCHECK" ]; then
  include sc_opts
fi

include styling

include banner
include no_arguments

include info_line
include error_done_wrap
include prompt_yes_no

include command/*.chunk.sh

include args_processing

chmod +x "$_out"
